server:
  port: 8092

spring:
  application:
    name: certifact-facturas-service-sp
  datasource:
    url: jdbc:postgresql://psetest-brasilia.cttrybvmh4sz.sa-east-1.rds.amazonaws.com/psetest
    username: psetest
    password: s0p0rt32019
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.certicom.certifact_facturas_service_sp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
